### ISSUE TITLE
Requires bash 4.x

### ISSUE THREAD

**Issue by Glennvd** [bAndie91/cloudflare-cli#1]
I was trying to figure out why I couldn't get this to work on OSX El Capitan, and it took me a while to realise I didn't have the correct version of bash installed. After installing this through brew and adjusting the script to use brew's version of bash it runs smoothly. Please consider adding this requirement to the docs somewhere, since a lot of webdevelopers use OSX.

**Comment by bAndie91** [comment]
you are right.

**Comment by bAndie91** [comment]
fixed in 48abce42e72eb7050e55e6e93b40978dd2729461

**Comment by fagiani** [comment]
I've got a bit distracted by this too even with the `README` improvement above. As the `declare -A` didn't call my attention to be a `bash` related issue. I've just created a PR #9 for improving that.

Hope it helps!

**Comment by bAndie91** [comment]
@fagiani, I really appreciate your effort. you drew my attention that we don't need associative arrays anymore, since it was used in APIv1 context. I removed it in recent commit.
However, it would be still prosperous to clarify which bash (and php) version does it work with.
Could you please investigate it?

**Comment by fagiani** [comment]
@bAndie91 Thanks for your quick attention on this.

Even with the latest commit, it looks like it still depends on bash 4 because of the syntax you're using in some lines like: `method=${1^^}` or `record_type=${2^^}` or `value=${value^^}` to get the values to become UPPERCASE. Although you could try using an alternative approach like the ones suggested [here](https://unix.stackexchange.com/questions/51983/bash-how-to-uppercase-the-command-line-argument) I'm not sure this is the only dependency. 

I guess the direction you will take here depends on whether you're looking for syntax simplicity vs. version compatibility. One aspect that I'd consider is that MacOS has been keeping `bash` on the 3.x versions for a while now mostly likely because of the `bash 4.x` license.

Anyway, with the current code, I believe the PR still makes sense in it's ultimate goal.

**Comment by bAndie91** [comment]
@fagiani, IMO we'd better constrain for the version, instead of back-port to bash 3 (as I use 4.2).
your code is merged, gratias.
